on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64, 386]
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
    - name: Build for ${{ matrix.goarch }}
      run: |
        GOOS=linux GOARCH=${{ matrix.goarch }} go build
    - name: Test for ${{ matrix.goarch }}
      run: |
        go test -v
      if: matrix.goarch == 'amd64'
